import Head from 'next/head'
import styles from '../styles/Layout.module.css'
import {AppWrapper} from '../context/state';

const Layout: React.FC = ({children}) => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next Asspp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {children}
      </main>
    </div>
  )
}

export default Layout;