import Head from 'next/head';
import React from 'react';
import styled from 'styled-components';

const Wrapper = styled.div`
  height: 100vh;
  width: 100vw;
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const Main = styled.main`
  background: white;
  width: 80vw;
  display: flex;
  flex-direction: column;
  justify-content: center;
  border-radius: 3rem;
  align-items: center;
  margin: auto;
  max-width: 120rem;
  box-shadow: 0 0 5rem rgba(0, 0, 0, 0.4);
  padding: 1rem;
`;

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props): JSX.Element => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>{children}</Main>
    </Wrapper>
  );
};

export default Layout;
